define([
	'common/module',
	'common/service/util',
	'common/service/interceptors',
	'common/service/ztree-util',
	'common/directive/modal/directive',
	'common/directive/page0/directive',
	'common/directive/repeatfinish/directive',
	'common/directive/autocomplete/directive',
	'common/directive/datepicker/directive',
	'common/directive/fileupload/directive',
	'common/directive/select2/directive',
	'common/directive/asynvalidation/directive',
	'common/filter',
	'common/service/myaes',
	'common/service/myrsa',
], function() {});
