require([
	'common/module',
	'common/service/interceptors',
	'common/service/myaes',
	'common/service/myrsa',
	'common/service/util',
	'common/service/ztree-util',
	'common/directive/modal/directive',
	'common/directive/pager/directive',
	'common/directive/repeatfinish/directive',
]);
